"""Tier-1 fixture tests: Python components vs the R reference implementation.

Fixtures are generated by ``validation_r/00_write_input_series.py`` +
``validation_r/01_export_component_fixtures.R`` and committed, so these tests
run without R. Tolerances are frozen in ``tests/fixtures/TOLERANCES.md`` —
do not widen them to make a failure pass; a failure means a regression.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest
from scipy.stats import ks_2samp

from baggets.bootstrap import moving_block_bootstrap
from baggets.boxcox import boxcox, guerrero_lambda
from baggets.decompose import decompose

MBB_SIDS = ["monthly_N1861", "synthetic_ar1"]


def load_cases(fixtures_dir):
    lambdas = pd.read_csv(fixtures_dir / "r_components" / "lambdas.csv")
    return [row for _, row in lambdas.iterrows()]


@pytest.fixture(scope="module")
def cases(fixtures_dir):
    rows = load_cases(fixtures_dir)
    out = {}
    for row in rows:
        sid = row["sid"]
        y = pd.read_csv(fixtures_dir / "input" / f"{sid}.csv")["y"].to_numpy(np.float64)
        comp = pd.read_csv(fixtures_dir / "r_components" / f"{sid}.csv")
        out[sid] = {"m": int(row["m"]), "lambda_r": float(row["lambda"]), "y": y, "comp": comp}
    return out


def all_sids(fixtures_dir):
    return [row["sid"] for row in load_cases(fixtures_dir)]


def pytest_generate_tests(metafunc):
    if "sid" in metafunc.fixturenames:
        from conftest import FIXTURES_DIR

        metafunc.parametrize("sid", all_sids(FIXTURES_DIR))


class TestGuerreroLambdaVsR:
    def test_lambda_matches(self, cases, sid):
        c = cases[sid]
        lam_py = guerrero_lambda(c["y"], c["m"], lower=0.0, upper=1.0)
        # Gate: |Δλ| ≤ 1e-3 (R optimize tol ~1.2e-4 near boundaries)
        assert abs(lam_py - c["lambda_r"]) <= 1e-3, (
            f"{sid}: lambda_py={lam_py:.6f} vs lambda_R={c['lambda_r']:.6f}"
        )


class TestBoxCoxVsR:
    def test_transform_matches_r_exactly(self, cases, sid):
        c = cases[sid]
        x_bc_py = boxcox(c["y"], c["lambda_r"])
        np.testing.assert_allclose(
            x_bc_py, c["comp"]["x_bc"].to_numpy(), rtol=1e-9, atol=1e-9,
            err_msg=f"{sid}: BoxCox transform diverges from R",
        )


class TestDecomposeVsR:
    def test_components_match(self, cases, sid):
        c = cases[sid]
        x_bc_r = c["comp"]["x_bc"].to_numpy()
        trend_r = c["comp"]["trend"].to_numpy()
        seasonal_r = c["comp"]["seasonal"].to_numpy()
        remainder_r = c["comp"]["remainder"].to_numpy()

        trend, seasonal, remainder = decompose(x_bc_r, c["m"])
        scale = x_bc_r.std()

        sd_ratio = remainder.std() / remainder_r.std()
        if c["m"] > 1:
            # STL is algorithmically identical to R (same netlib lineage, same
            # windows/jumps/iterations): machine-precision gates.
            assert np.max(np.abs(trend - trend_r)) <= 1e-9 * scale, f"{sid}: trend"
            assert np.max(np.abs(seasonal - seasonal_r)) <= 1e-9 * scale, f"{sid}: seasonal"
            assert abs(sd_ratio - 1.0) <= 1e-6, f"{sid}: remainder sd ratio {sd_ratio:.8f}"
        else:
            # loess: different implementation (statsmodels lowess exact vs R
            # kd-tree interpolation) — tight but not exact.
            assert np.max(np.abs(trend - trend_r)) <= 1e-3 * scale, f"{sid}: loess trend"
            corr = np.corrcoef(trend, trend_r)[0, 1]
            assert corr >= 0.999, f"{sid}: loess trend corr {corr:.5f}"
            assert abs(sd_ratio - 1.0) <= 1e-3, f"{sid}: remainder sd ratio {sd_ratio:.6f}"


class TestMBBVsR:
    @pytest.mark.parametrize("mbb_sid", MBB_SIDS)
    def test_draw_distributions_match(self, fixtures_dir, cases, mbb_sid):
        c = cases[mbb_sid]
        remainder_r = c["comp"]["remainder"].to_numpy()
        block_size = 2 * c["m"] if c["m"] > 1 else 8

        r_sd = pd.read_csv(fixtures_dir / "r_mbb" / f"{mbb_sid}_perdraw_sd.csv")["sd"].to_numpy()
        r_pooled = pd.read_csv(fixtures_dir / "r_mbb" / f"{mbb_sid}_pooled.csv")["value"].to_numpy()

        rng = np.random.default_rng(123)
        draws = [moving_block_bootstrap(remainder_r, block_size, rng) for _ in range(2000)]
        py_sd = np.array([d.std(ddof=1) for d in draws])
        py_pooled = np.concatenate(draws[:50])

        # Same source remainder, same mechanics -> distributions indistinguishable
        assert ks_2samp(py_sd, r_sd).pvalue > 0.01, f"{mbb_sid}: per-draw sd KS"
        assert ks_2samp(py_pooled, r_pooled).pvalue > 0.01, f"{mbb_sid}: pooled values KS"
